
-- folder locations
FOLDER = {}
FOLDER.ASSETS = "game/assets/"
FOLDER.PARTICLESYSTEMS = "game/assets/particlesystems/"

-- input constants
MOUSE = {}
MOUSE.LEFT = "l"
MOUSE.RIGHT = "r"
MOUSE.MIDDLE = "m"
MOUSE.WHEELDOWN = "wd"
MOUSE.WHEELUP = "wu"
MOUSE.BUTTON4 = "x1"
MOUSE.BUTTON5 = "x2"

-- draw layer order
DRAW_LAYER = {}
DRAW_LAYER.TOP = -1
DRAW_LAYER.BOTTOM = 99999

-- draw layer types
LAYER_TYPE = {}
LAYER_TYPE.NONE = 0
LAYER_TYPE.IMAGES = 1
LAYER_TYPE.BATCH = 2
LAYER_TYPE.BACKGROUND = 3
LAYER_TYPE.CUSTOM = 4

-- screen scaling types
SCREEN_SCALE = {}
SCREEN_SCALE.CENTRE = 0
SCREEN_SCALE.STRETCH = 1
SCREEN_SCALE.FIT_BEST_LETTERBOX = 2
SCREEN_SCALE.FIT_BEST_CLIPEDGES = 3
SCREEN_SCALE.FIT_HEIGHT = 4
SCREEN_SCALE.FIT_WIDTH = 5