
-- folder locations
FOLDER = {}
FOLDER.ASSETS = "game/assets/"

-- input constants
MOUSE = {}
MOUSE.LEFT = "l"
MOUSE.RIGHT = "r"
MOUSE.MIDDLE = "m"
MOUSE.WHEELDOWN = "wd"
MOUSE.WHEELUP = "wu"
MOUSE.BUTTON4 = "x1"
MOUSE.BUTTON5 = "x2"

-- draw layer order
DRAW_LAYER_TOP = -1
DRAW_LAYER_BOTTOM = 99999

-- draw layer types
LAYER_TYPE_NONE = 0
LAYER_TYPE_IMAGES = 1
LAYER_TYPE_BATCH = 2
LAYER_TYPE_BACKGROUND = 3
LAYER_TYPE_CUSTOM = 4